#!/bin/bash

#if .bash dir doesn't exist, create it
rootdir=$HOME"/.bash"
repobashhome=$PWD
if [ -d $rootdir ] ; then
  mv $rootdir $rootdir`ls -d $rootdir*".old" | wc -l`".old"
fi

echo "Creating $rootdir"
mkdir $rootdir


dirs="functions vars aliases completion themes"
for dir in $dirs; do
    if [ ! -d $rootdir"/"$dir ]
    then
        echo "Linking $rootdir/$dir to $PWD/bash/$dir"
        ln -s $PWD"/bash/dot_mybash/"$dir $rootdir"/"$dir
    fi
done

customdir=$rootdir"/custom"
if [ ! -d $customdir ]; then
  echo "Creating $customdir"
  ln -s $PWD"/bash/dot_mybash/custom" $rootdir"/custom"
fi

#add tmux.conf
#add vimrc

#add bin
if [ -d $HOME"/bin" ]; then
  mv $HOME"/bin" $HOME"/local_bin"`ls -d $HOME"/local_bin"* | wc -l`
fi
ln -sf $PWD"/home_bin" $HOME"/bin"

inputrc=$HOME"/.inputrc" 
if [ -f $inputrc ] ; then
  mv $inputrc $inputrc `ls -d $inputrc* | wc -l`".old"
fi
ln -sf $PWD"/bash/dot_inputrc" $inputrc

bashrc=$HOME"/.bashrc" 
if [ -f $bashrc ] ; then
  mv $bashrc $bashrc`ls -d $bashrc* | wc -l`".old"
fi
ln -sf $PWD"/bash/dot_bashrc" $bashrc

