" set colors
"colorscheme solarized
"solarized8 from https://vimawesome.com/plugin/solarized-8
set background=light
colorscheme solarized8

" enable syntax highlighting
syntax enable

" show line numbers
set number

" set tabs to have 4 spaces
set ts=4

" indent when moving to the next line while writing code
set autoindent

" expand tabs into spaces
set expandtab

" when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4

" show a visual line under the cursor's current line
set cursorline

" show the matching part of the pair for [] {} and ()
set showmatch

" enable all Python syntax highlighting features
let python_highlight_all = 1

" set column 80 to color (python style guide says no line longer than 79
set colorcolumn=80

" wrap lines longer than width of screen
set wrap linebreak nolist

" set the ruler on
set ruler

" allow hidden buffers to be modified
set hidden

" keep the cursor from going to the very top or bottom
set scrolloff=7

"set kj to Esc to leave insert mode
:imap kj <Esc>

" key mapping
" set caps lock to ctrl and unset it when exiting
au VimEnter * silent! !setxkbmap -option caps:ctrl_modifier
au VimLeave * silent! !setxkbmap -option

" set the path to all subdirectories from current directory
set path=$PWD/**
