#!/bin/bash


function use()
{
    echo `basename $0`" <makefile or project>"
}



unset arg
if [ "$#" -eq "1" ]; then
    arg=$1
else
    if [ -f "GNUmakefile" ]; then
        arg="GNUmakefile";
    elif [ -f "makefile" ]; then
        arg="makefile";
    elif [ -f "Makefile" ]; then
        arg="Makefile"
    else
        use
        exit -1
    fi
fi



if [ -f "$arg" ]; then
    makefile=$arg
else
    makefile="makefile."$arg
fi

if [ ! -f "$makefile" ]; then
    echo "ERROR -- cannot find makefile "$makefile
    use
    exit -1
fi



echo
echo "--- Using "$makefile" ---"
echo



source ~/.functions


scr=`basename $0`
targets=

if [ "build" == "$scr" ]; then
    targets="install"
elif [ "clean" == "$scr" ]; then
    targets="distclean uninstall"
else
    echo "ERROR -- I do not know what to do ("$scr")"
fi


debug
for x in $targets; do
    nice make -j 2 -f $makefile $x
    if [ "0" -ne "$?" ]; then
        echo "Failed to $scr for DEBUG"
        exit -1
    fi
done

release
for x in $targets; do
    nice make -j 2 -f $makefile $x
    if [ "0" -ne "$?" ]; then
        echo "Failed to $scr for RELEASE"
        exit -1
    fi
done
